//=========================================================
// src/lamp_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <state_machine.h>
#include <SI_EFM8BB52_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
#include "timer_4.h"

// $[Generated Includes]
// [Generated Includes]$

// Mask of all five buttons within PORT3.
#define P3_BTN_BMASK (P3_B4__BMASK | P3_B3__BMASK | P3_B2__BMASK \
                      | P3_B1__BMASK | P3_B0__BMASK)

//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void
SiLabs_Startup(void)
{
  // $[SiLabs Startup]
  // [SiLabs Startup]$
}






int main(void) {
  event_t event;

  // Call hardware initialization routine
  enter_DefaultMode_from_RESET ();

  // Set all the button pins high.
  // Because the pins are configured as open-drain, setting them high disables
  // their MOSFETs (which would otherwise pull down against their internal
  // pullup resistors and external pullups, if present) and lets the pullups
  // pull them high.
  // Then, when they are externally pulled low by the user pressing the tactile
  // switches, we will be able to read this as a change in this very same PORT3
  // register.
  P3 |= P3_BTN_BMASK;


  // Main loop
  while (1){
      // $[Generated Run-time code]
      // [Generated Run-time code]$

      // Fetch current event, run the state machine, and delay
      event = fetch_event();
      state_machine_run_iteration(event);
      timer_4_delay_ms(STATE_MACHINE_PERIOD);
    }
}
