/*
 * efm8_config.h
 *
 *  Created on: Feb 26, 2023
 *      Author: elass
 */

#ifndef INC_EFM8_CONFIG_H_
#define INC_EFM8_CONFIG_H_

#define EFM8PDL_SMB0_AUTO_PAGE 1
#define EFM8PDL_SMB0_USE_STATEMACHINE 0
#define EFM8PDL_SMB0_USE_BUFFER 1

#define EFM8PDL_SMB0_MASTER_RETRIES 1

#define EFM8PDL_SMB0_TX_BUFTYPE SI_SEG_XDATA
#define EFM8PDL_SMB0_RX_BUFTYPE SI_SEG_XDATA

#endif /* INC_EFM8_CONFIG_H_ */
